json.id               event.id
json.event_date       event.event_date
json.event_type       event.event_type
json.actor1           event.actor1
json.actor2           event.actor2
json.country          event.country
json.source           event.source
json.notes            event.notes
json.total_fatalities event.total_fatalities
json.latitude         event.latitude
json.longitude        event.longitude
json.created_at       event.created_at
json.updated_at       event.updated_at
